### ISSUE TITLE
bootstrap CSS stylesheet for search result

### ISSUE THREAD

**Issue by Jeffchiucp** [anselb/activity-planner#11]
Need to make sure all of the image are the same size <img width="841" alt="screen shot 2017-12-12 at 4 15 26 pm" src="https://user-images.githubusercontent.com/10523517/33915385-f003f992-df57-11e7-8d68-b02a884fae74.png">

**Comment by Jeffchiucp** [comment]
need to fix the image size

**Comment by Jeffchiucp** [comment]
CSS update is in Progress

**Comment by Jeffchiucp** [comment]
in progress

**Comment by JeffChiu2009** [comment]
Do you need any help on CSS?

**Comment by Jeffchiucp** [comment]
working in progress | needed to use flexbox

**Comment by Jeffchiucp** [comment]
pushed this feature request in the end
