### ISSUE TITLE
Dates Formatting request. Remove the extraneous information.

### ISSUE THREAD

**Issue by JeffChiu2009** [anselb/activity-planner#53]
Dates on itinerary index and individual itinerary provide extraneous information.
<img width="1386" alt="screen shot 2018-01-31 at 6 50 45 pm" src="https://user-images.githubusercontent.com/7025757/35699001-98c0ea6e-0743-11e8-8701-0b24be26c80c.png">

#needed to correct the dates instead of showing "PST" or "UTC"

https://github.com/anselb/activity-planner/blob/136217cf0f6317960d9a6d753c65d5e452132faf/views/index.jade#L34

**Comment by Jeffchiucp** [comment]
update the date formatting and now it should be working Okay.

**Comment by Jeffchiucp** [comment]
fixed the issue for date formatting <img width="1361" alt="screen shot 2018-02-01 at 12 40 56 pm" src="https://user-images.githubusercontent.com/10523517/35702173-3eef7fa0-074d-11e8-9faf-848a6e679617.png">

**Comment by Jeffchiucp** [comment]
closed the issue
